# Generated by Django 5.1.7 on 2025-03-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_type_of_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=10, unique=True)),
                ('course_desc', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments')),
            ],
        ),
    ]
