# Generated by Django 5.1.7 on 2025-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
