# Generated by Django 5.1.7 on 2025-03-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_courses_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('path_of_module', models.CharField(max_length=100, unique=True)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
            ],
        ),
    ]
