# Generated by Django 5.1.7 on 2025-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_modulecreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='path_of_module',
            field=models.CharField(max_length=100),
        ),
    ]
