# Generated by Django 5.1.7 on 2025-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_modules_module_id_alter_modules_path_of_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
