# Generated by Django 5.1.7 on 2025-03-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_modules_module_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses'),
        ),
    ]
