# Generated by Django 5.1.7 on 2025-03-31 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_modules_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_completed', models.IntegerField()),
                ('quizes_completed', models.IntegerField()),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
        ),
    ]
