# Generated by Django 5.1.7 on 2025-04-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_studentmoduelcompleted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructor',
            new_name='Instructors',
        ),
        migrations.RenameModel(
            old_name='StudentModuelCompleted',
            new_name='StudentModuleCompleted',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('instructor', 'Instructor')], default='admin', max_length=11),
        ),
    ]
