# Generated by Django 5.1.7 on 2025-04-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_instructor_instructors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='year',
        ),
    ]
