# Generated by Django 5.1.7 on 2025-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_students_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='number_of_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departments',
            name='number_of_instructors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departments',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
