# Generated by Django 5.1.7 on 2025-04-06 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_courses_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursedetail',
            name='modules_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcoursedetail',
            name='quizes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructors')),
            ],
        ),
    ]
