# Generated by Django 5.1.7 on 2025-04-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_studentcoursedetail_modules_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcoursedetail',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_students', to='api.courses'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_teachers', to='api.courses'),
        ),
    ]
