# Generated by Django 5.1.7 on 2025-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_studentcoursedetail_course_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcoursedetail',
            unique_together={('student_id', 'course_id')},
        ),
    ]
