# Generated by Django 5.1.7 on 2025-04-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_studentcoursedetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecreator',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_creators', to='api.modules'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('path_of_quiz', models.CharField(max_length=20)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructors')),
            ],
        ),
    ]
