# Generated by Django 5.1.7 on 2025-04-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_quiz_description_alter_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
