# Generated by Django 5.1.7 on 2025-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='answers',
            field=models.CharField(max_length=1000),
        ),
    ]
