# Generated by Django 5.1.7 on 2025-04-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_quizsubmission_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsubmission',
            name='marks',
        ),
    ]
