# Generated by Django 5.1.7 on 2025-04-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_quizsubmission_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='department_id',
            new_name='department',
        ),
    ]
