# Generated by Django 5.1.7 on 2025-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_department_id_students_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='user_id',
            new_name='user',
        ),
    ]
