# Generated by Django 5.1.7 on 2025-04-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_user_id_students_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='department_id',
            new_name='id',
        ),
    ]
