# Generated by Django 5.1.7 on 2025-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_department_id_departments_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='id',
            new_name='department_id',
        ),
    ]
