# Generated by Django 5.1.7 on 2025-04-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_id_departments_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructors',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='instructors',
            old_name='user_id',
            new_name='user',
        ),
    ]
