# Generated by Django 5.1.7 on 2025-04-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_department_id_instructors_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='department_id',
            new_name='department',
        ),
    ]
