# Generated by Django 5.1.7 on 2025-04-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_department_id_courses_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcoursedetail',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentcoursedetail',
            old_name='student_id',
            new_name='student',
        ),
    ]
