# Generated by Django 5.1.7 on 2025-04-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_course_id_studentcoursedetail_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentmodulecompleted',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentmodulecompleted',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='studentmodulecompleted',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='instructor_id',
            new_name='instructor',
        ),
    ]
