# Generated by Django 5.1.7 on 2025-04-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_course_id_quiz_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='course_id',
            new_name='course',
        ),
    ]
