# Generated by Django 5.1.7 on 2025-04-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_course_id_modules_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulecreator',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='modulecreator',
            old_name='module_id',
            new_name='module',
        ),
    ]
